# Generated by Django 4.0.6 on 2022-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(choices=[('car', 'car'), ('micro', 'micro'), ('bike', 'bike'), ('pickup', 'pickup'), ('miniBus', 'miniBus'), ('bus', 'bus')], default='car', max_length=10)),
                ('vehicleName', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('regNum', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('vehicleCondition', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=5)),
                ('bookingContact', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
